// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class LYCheckin;
@class LYCheckin_Builder;
@class TrackEvent;
@class TrackEvent_Builder;
typedef enum {
  LYOsTypeLyAndroid = 0,
  LYOsTypeLyIos = 1,
  LYOsTypeLyWp = 2,
} LYOsType;

BOOL LYOsTypeIsValidValue(LYOsType value);

typedef enum {
  TrackEvent_EventTypeLyCheckIn = 100,
  TrackEvent_EventTypeStartTrackingReq = 120,
  TrackEvent_EventTypeStartTrackingRep = 210,
  TrackEvent_EventTypeSendLocReq = 320,
  TrackEvent_EventTypeSendLocRep = 230,
  TrackEvent_EventTypeQueryByIdReq = 321,
  TrackEvent_EventTypeQueryByIdRep = 231,
  TrackEvent_EventTypeFwdLocReq = 211,
  TrackEvent_EventTypeFwdLocRep = 121,
} TrackEvent_EventType;

BOOL TrackEvent_EventTypeIsValidValue(TrackEvent_EventType value);


@interface TrackeventRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface TrackEvent : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasTracker_:1;
  BOOL hasTrackerX_:1;
  BOOL hasTrackerY_:1;
  BOOL hasTrackee_:1;
  BOOL hasTrackeeX_:1;
  BOOL hasTrackeeY_:1;
  BOOL hasTrackeeDesc_:1;
  BOOL hasSndId_:1;
  BOOL hasCheckin_:1;
  BOOL hasType_:1;
  int32_t id;
  NSString* tracker;
  NSString* trackerX;
  NSString* trackerY;
  NSString* trackee;
  NSString* trackeeX;
  NSString* trackeeY;
  NSString* trackeeDesc;
  NSString* sndId;
  LYCheckin* checkin;
  TrackEvent_EventType type;
}
- (BOOL) hasType;
- (BOOL) hasId;
- (BOOL) hasTracker;
- (BOOL) hasTrackerX;
- (BOOL) hasTrackerY;
- (BOOL) hasTrackee;
- (BOOL) hasTrackeeX;
- (BOOL) hasTrackeeY;
- (BOOL) hasTrackeeDesc;
- (BOOL) hasCheckin;
- (BOOL) hasSndId;
@property (readonly) TrackEvent_EventType type;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* tracker;
@property (readonly, retain) NSString* trackerX;
@property (readonly, retain) NSString* trackerY;
@property (readonly, retain) NSString* trackee;
@property (readonly, retain) NSString* trackeeX;
@property (readonly, retain) NSString* trackeeY;
@property (readonly, retain) NSString* trackeeDesc;
@property (readonly, retain) LYCheckin* checkin;
@property (readonly, retain) NSString* sndId;

+ (TrackEvent*) defaultInstance;
- (TrackEvent*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TrackEvent_Builder*) builder;
+ (TrackEvent_Builder*) builder;
+ (TrackEvent_Builder*) builderWithPrototype:(TrackEvent*) prototype;

+ (TrackEvent*) parseFromData:(NSData*) data;
+ (TrackEvent*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TrackEvent*) parseFromInputStream:(NSInputStream*) input;
+ (TrackEvent*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TrackEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TrackEvent*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TrackEvent_Builder : PBGeneratedMessage_Builder {
@private
  TrackEvent* result;
}

- (TrackEvent*) defaultInstance;

- (TrackEvent_Builder*) clear;
- (TrackEvent_Builder*) clone;

- (TrackEvent*) build;
- (TrackEvent*) buildPartial;

- (TrackEvent_Builder*) mergeFrom:(TrackEvent*) other;
- (TrackEvent_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TrackEvent_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (TrackEvent_EventType) type;
- (TrackEvent_Builder*) setType:(TrackEvent_EventType) value;
- (TrackEvent_Builder*) clearType;

- (BOOL) hasId;
- (int32_t) id;
- (TrackEvent_Builder*) setId:(int32_t) value;
- (TrackEvent_Builder*) clearId;

- (BOOL) hasTracker;
- (NSString*) tracker;
- (TrackEvent_Builder*) setTracker:(NSString*) value;
- (TrackEvent_Builder*) clearTracker;

- (BOOL) hasTrackerX;
- (NSString*) trackerX;
- (TrackEvent_Builder*) setTrackerX:(NSString*) value;
- (TrackEvent_Builder*) clearTrackerX;

- (BOOL) hasTrackerY;
- (NSString*) trackerY;
- (TrackEvent_Builder*) setTrackerY:(NSString*) value;
- (TrackEvent_Builder*) clearTrackerY;

- (BOOL) hasTrackee;
- (NSString*) trackee;
- (TrackEvent_Builder*) setTrackee:(NSString*) value;
- (TrackEvent_Builder*) clearTrackee;

- (BOOL) hasTrackeeX;
- (NSString*) trackeeX;
- (TrackEvent_Builder*) setTrackeeX:(NSString*) value;
- (TrackEvent_Builder*) clearTrackeeX;

- (BOOL) hasTrackeeY;
- (NSString*) trackeeY;
- (TrackEvent_Builder*) setTrackeeY:(NSString*) value;
- (TrackEvent_Builder*) clearTrackeeY;

- (BOOL) hasTrackeeDesc;
- (NSString*) trackeeDesc;
- (TrackEvent_Builder*) setTrackeeDesc:(NSString*) value;
- (TrackEvent_Builder*) clearTrackeeDesc;

- (BOOL) hasCheckin;
- (LYCheckin*) checkin;
- (TrackEvent_Builder*) setCheckin:(LYCheckin*) value;
- (TrackEvent_Builder*) setCheckinBuilder:(LYCheckin_Builder*) builderForValue;
- (TrackEvent_Builder*) mergeCheckin:(LYCheckin*) value;
- (TrackEvent_Builder*) clearCheckin;

- (BOOL) hasSndId;
- (NSString*) sndId;
- (TrackEvent_Builder*) setSndId:(NSString*) value;
- (TrackEvent_Builder*) clearSndId;
@end

@interface LYCheckin : PBGeneratedMessage {
@private
  BOOL hasLyMajorRelease_:1;
  BOOL hasLyMinorRelease_:1;
  BOOL hasDeviceModel_:1;
  BOOL hasOsVersion_:1;
  BOOL hasDownloadUrl_:1;
  BOOL hasDesc_:1;
  BOOL hasOsType_:1;
  int32_t lyMajorRelease;
  int32_t lyMinorRelease;
  NSString* deviceModel;
  NSString* osVersion;
  NSString* downloadUrl;
  NSString* desc;
  LYOsType osType;
}
- (BOOL) hasDeviceModel;
- (BOOL) hasOsType;
- (BOOL) hasOsVersion;
- (BOOL) hasLyMajorRelease;
- (BOOL) hasLyMinorRelease;
- (BOOL) hasDownloadUrl;
- (BOOL) hasDesc;
@property (readonly, retain) NSString* deviceModel;
@property (readonly) LYOsType osType;
@property (readonly, retain) NSString* osVersion;
@property (readonly) int32_t lyMajorRelease;
@property (readonly) int32_t lyMinorRelease;
@property (readonly, retain) NSString* downloadUrl;
@property (readonly, retain) NSString* desc;

+ (LYCheckin*) defaultInstance;
- (LYCheckin*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYCheckin_Builder*) builder;
+ (LYCheckin_Builder*) builder;
+ (LYCheckin_Builder*) builderWithPrototype:(LYCheckin*) prototype;

+ (LYCheckin*) parseFromData:(NSData*) data;
+ (LYCheckin*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYCheckin*) parseFromInputStream:(NSInputStream*) input;
+ (LYCheckin*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYCheckin*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYCheckin*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYCheckin_Builder : PBGeneratedMessage_Builder {
@private
  LYCheckin* result;
}

- (LYCheckin*) defaultInstance;

- (LYCheckin_Builder*) clear;
- (LYCheckin_Builder*) clone;

- (LYCheckin*) build;
- (LYCheckin*) buildPartial;

- (LYCheckin_Builder*) mergeFrom:(LYCheckin*) other;
- (LYCheckin_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYCheckin_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeviceModel;
- (NSString*) deviceModel;
- (LYCheckin_Builder*) setDeviceModel:(NSString*) value;
- (LYCheckin_Builder*) clearDeviceModel;

- (BOOL) hasOsType;
- (LYOsType) osType;
- (LYCheckin_Builder*) setOsType:(LYOsType) value;
- (LYCheckin_Builder*) clearOsType;

- (BOOL) hasOsVersion;
- (NSString*) osVersion;
- (LYCheckin_Builder*) setOsVersion:(NSString*) value;
- (LYCheckin_Builder*) clearOsVersion;

- (BOOL) hasLyMajorRelease;
- (int32_t) lyMajorRelease;
- (LYCheckin_Builder*) setLyMajorRelease:(int32_t) value;
- (LYCheckin_Builder*) clearLyMajorRelease;

- (BOOL) hasLyMinorRelease;
- (int32_t) lyMinorRelease;
- (LYCheckin_Builder*) setLyMinorRelease:(int32_t) value;
- (LYCheckin_Builder*) clearLyMinorRelease;

- (BOOL) hasDownloadUrl;
- (NSString*) downloadUrl;
- (LYCheckin_Builder*) setDownloadUrl:(NSString*) value;
- (LYCheckin_Builder*) clearDownloadUrl;

- (BOOL) hasDesc;
- (NSString*) desc;
- (LYCheckin_Builder*) setDesc:(NSString*) value;
- (LYCheckin_Builder*) clearDesc;
@end

