// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class LYCityTraffic;
@class LYCityTraffic_Builder;
@class LYCoordinate;
@class LYCoordinate_Builder;
@class LYCrontab;
@class LYCrontab_Builder;
@class LYDeviceReport;
@class LYDeviceReport_Builder;
@class LYLocation;
@class LYLocation_Builder;
@class LYMsgOnAir;
@class LYMsgOnAir_Builder;
@class LYRoadTraffic;
@class LYRoadTraffic_Builder;
@class LYRoute;
@class LYRoute_Builder;
@class LYSamplePoint;
@class LYSamplePoint_Builder;
@class LYSegment;
@class LYSegmentTraffic;
@class LYSegmentTraffic_Builder;
@class LYSegment_Builder;
@class LYTrafficPub;
@class LYTrafficPub_Builder;
@class LYTrafficReport;
@class LYTrafficReport_Builder;
@class LYTrafficSub;
@class LYTrafficSub_Builder;
typedef enum {
  LYDirectionLyUnknown = 0,
  LYDirectionLyEast = 1,
  LYDirectionLyNortheast = 2,
  LYDirectionLyNorth = 3,
  LYDirectionLyNorthwest = 4,
  LYDirectionLyWest = 5,
  LYDirectionLySouthwest = 6,
  LYDirectionLySouth = 7,
  LYDirectionLySoutheast = 8,
} LYDirection;

BOOL LYDirectionIsValidValue(LYDirection value);

typedef enum {
  LYRetCodeLySuccess = 0,
  LYRetCodeLyVersionImcompatible = 273,
  LYRetCodeLyVersionLow = 291,
  LYRetCodeLyPartyError = 553,
  LYRetCodeLyMsgTypeError = 914,
  LYRetCodeLyTimeout = 1171,
  LYRetCodeLyOtherError = 2457,
} LYRetCode;

BOOL LYRetCodeIsValidValue(LYRetCode value);

typedef enum {
  LYPartyLyClient = 1,
  LYPartyLyTss = 2,
} LYParty;

BOOL LYPartyIsValidValue(LYParty value);

typedef enum {
  LYMsgTypeLyVoid = 1,
  LYMsgTypeLyRetCode = 2,
  LYMsgTypeLyTrafficSub = 4,
  LYMsgTypeLyTrafficReport = 5,
  LYMsgTypeLyDeviceReport = 6,
  LYMsgTypeLyTrafficPub = 19,
} LYMsgType;

BOOL LYMsgTypeIsValidValue(LYMsgType value);

typedef enum {
  LYCrontab_LYCronTypeLyRepMinute = 1,
  LYCrontab_LYCronTypeLyRepHour = 2,
  LYCrontab_LYCronTypeLyRepDom = 4,
  LYCrontab_LYCronTypeLyRepMonth = 8,
  LYCrontab_LYCronTypeLyRepDow = 16,
} LYCrontab_LYCronType;

BOOL LYCrontab_LYCronTypeIsValidValue(LYCrontab_LYCronType value);

typedef enum {
  LYTrafficSub_LYOprTypeLySubCreate = 1,
  LYTrafficSub_LYOprTypeLySubDelete = 2,
  LYTrafficSub_LYOprTypeLySubUpdate = 3,
} LYTrafficSub_LYOprType;

BOOL LYTrafficSub_LYOprTypeIsValidValue(LYTrafficSub_LYOprType value);

typedef enum {
  LYTrafficSub_LYPubTypeLyPubAdhoc = 1,
  LYTrafficSub_LYPubTypeLyPubEvent = 2,
  LYTrafficSub_LYPubTypeLyPubCron = 3,
} LYTrafficSub_LYPubType;

BOOL LYTrafficSub_LYPubTypeIsValidValue(LYTrafficSub_LYPubType value);


@interface TssRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface LYCoordinate : PBGeneratedMessage {
@private
  BOOL hasLng_:1;
  BOOL hasLat_:1;
  Float64 lng;
  Float64 lat;
}
- (BOOL) hasLng;
- (BOOL) hasLat;
@property (readonly) Float64 lng;
@property (readonly) Float64 lat;

+ (LYCoordinate*) defaultInstance;
- (LYCoordinate*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYCoordinate_Builder*) builder;
+ (LYCoordinate_Builder*) builder;
+ (LYCoordinate_Builder*) builderWithPrototype:(LYCoordinate*) prototype;

+ (LYCoordinate*) parseFromData:(NSData*) data;
+ (LYCoordinate*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYCoordinate*) parseFromInputStream:(NSInputStream*) input;
+ (LYCoordinate*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYCoordinate*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYCoordinate*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYCoordinate_Builder : PBGeneratedMessage_Builder {
@private
  LYCoordinate* result;
}

- (LYCoordinate*) defaultInstance;

- (LYCoordinate_Builder*) clear;
- (LYCoordinate_Builder*) clone;

- (LYCoordinate*) build;
- (LYCoordinate*) buildPartial;

- (LYCoordinate_Builder*) mergeFrom:(LYCoordinate*) other;
- (LYCoordinate_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYCoordinate_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLng;
- (Float64) lng;
- (LYCoordinate_Builder*) setLng:(Float64) value;
- (LYCoordinate_Builder*) clearLng;

- (BOOL) hasLat;
- (Float64) lat;
- (LYCoordinate_Builder*) setLat:(Float64) value;
- (LYCoordinate_Builder*) clearLat;
@end

@interface LYLocation : PBGeneratedMessage {
@private
  BOOL hasLng_:1;
  BOOL hasLat_:1;
  BOOL hasName_:1;
  BOOL hasAdt_:1;
  Float64 lng;
  Float64 lat;
  NSString* name;
  NSString* adt;
}
- (BOOL) hasLng;
- (BOOL) hasLat;
- (BOOL) hasName;
- (BOOL) hasAdt;
@property (readonly) Float64 lng;
@property (readonly) Float64 lat;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* adt;

+ (LYLocation*) defaultInstance;
- (LYLocation*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYLocation_Builder*) builder;
+ (LYLocation_Builder*) builder;
+ (LYLocation_Builder*) builderWithPrototype:(LYLocation*) prototype;

+ (LYLocation*) parseFromData:(NSData*) data;
+ (LYLocation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYLocation*) parseFromInputStream:(NSInputStream*) input;
+ (LYLocation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYLocation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYLocation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYLocation_Builder : PBGeneratedMessage_Builder {
@private
  LYLocation* result;
}

- (LYLocation*) defaultInstance;

- (LYLocation_Builder*) clear;
- (LYLocation_Builder*) clone;

- (LYLocation*) build;
- (LYLocation*) buildPartial;

- (LYLocation_Builder*) mergeFrom:(LYLocation*) other;
- (LYLocation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYLocation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLng;
- (Float64) lng;
- (LYLocation_Builder*) setLng:(Float64) value;
- (LYLocation_Builder*) clearLng;

- (BOOL) hasLat;
- (Float64) lat;
- (LYLocation_Builder*) setLat:(Float64) value;
- (LYLocation_Builder*) clearLat;

- (BOOL) hasName;
- (NSString*) name;
- (LYLocation_Builder*) setName:(NSString*) value;
- (LYLocation_Builder*) clearName;

- (BOOL) hasAdt;
- (NSString*) adt;
- (LYLocation_Builder*) setAdt:(NSString*) value;
- (LYLocation_Builder*) clearAdt;
@end

@interface LYSegment : PBGeneratedMessage {
@private
  BOOL hasRoad_:1;
  BOOL hasStart_:1;
  BOOL hasEnd_:1;
  NSString* road;
  LYCoordinate* start;
  LYCoordinate* end;
}
- (BOOL) hasStart;
- (BOOL) hasEnd;
- (BOOL) hasRoad;
@property (readonly, retain) LYCoordinate* start;
@property (readonly, retain) LYCoordinate* end;
@property (readonly, retain) NSString* road;

+ (LYSegment*) defaultInstance;
- (LYSegment*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYSegment_Builder*) builder;
+ (LYSegment_Builder*) builder;
+ (LYSegment_Builder*) builderWithPrototype:(LYSegment*) prototype;

+ (LYSegment*) parseFromData:(NSData*) data;
+ (LYSegment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYSegment*) parseFromInputStream:(NSInputStream*) input;
+ (LYSegment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYSegment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYSegment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYSegment_Builder : PBGeneratedMessage_Builder {
@private
  LYSegment* result;
}

- (LYSegment*) defaultInstance;

- (LYSegment_Builder*) clear;
- (LYSegment_Builder*) clone;

- (LYSegment*) build;
- (LYSegment*) buildPartial;

- (LYSegment_Builder*) mergeFrom:(LYSegment*) other;
- (LYSegment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYSegment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStart;
- (LYCoordinate*) start;
- (LYSegment_Builder*) setStart:(LYCoordinate*) value;
- (LYSegment_Builder*) setStartBuilder:(LYCoordinate_Builder*) builderForValue;
- (LYSegment_Builder*) mergeStart:(LYCoordinate*) value;
- (LYSegment_Builder*) clearStart;

- (BOOL) hasEnd;
- (LYCoordinate*) end;
- (LYSegment_Builder*) setEnd:(LYCoordinate*) value;
- (LYSegment_Builder*) setEndBuilder:(LYCoordinate_Builder*) builderForValue;
- (LYSegment_Builder*) mergeEnd:(LYCoordinate*) value;
- (LYSegment_Builder*) clearEnd;

- (BOOL) hasRoad;
- (NSString*) road;
- (LYSegment_Builder*) setRoad:(NSString*) value;
- (LYSegment_Builder*) clearRoad;
@end

@interface LYRoute : PBGeneratedMessage {
@private
  BOOL hasIdentity_:1;
  int32_t identity;
  NSMutableArray* mutableSegmentsList;
}
- (BOOL) hasIdentity;
@property (readonly) int32_t identity;
- (NSArray*) segmentsList;
- (LYSegment*) segmentsAtIndex:(int32_t) index;

+ (LYRoute*) defaultInstance;
- (LYRoute*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYRoute_Builder*) builder;
+ (LYRoute_Builder*) builder;
+ (LYRoute_Builder*) builderWithPrototype:(LYRoute*) prototype;

+ (LYRoute*) parseFromData:(NSData*) data;
+ (LYRoute*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYRoute*) parseFromInputStream:(NSInputStream*) input;
+ (LYRoute*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYRoute*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYRoute*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYRoute_Builder : PBGeneratedMessage_Builder {
@private
  LYRoute* result;
}

- (LYRoute*) defaultInstance;

- (LYRoute_Builder*) clear;
- (LYRoute_Builder*) clone;

- (LYRoute*) build;
- (LYRoute*) buildPartial;

- (LYRoute_Builder*) mergeFrom:(LYRoute*) other;
- (LYRoute_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYRoute_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIdentity;
- (int32_t) identity;
- (LYRoute_Builder*) setIdentity:(int32_t) value;
- (LYRoute_Builder*) clearIdentity;

- (NSArray*) segmentsList;
- (LYSegment*) segmentsAtIndex:(int32_t) index;
- (LYRoute_Builder*) replaceSegmentsAtIndex:(int32_t) index with:(LYSegment*) value;
- (LYRoute_Builder*) addSegments:(LYSegment*) value;
- (LYRoute_Builder*) addAllSegments:(NSArray*) values;
- (LYRoute_Builder*) clearSegmentsList;
@end

@interface LYSegmentTraffic : PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasSpeed_:1;
  BOOL hasDetails_:1;
  BOOL hasSegment_:1;
  BOOL hasDirection_:1;
  int64_t timestamp;
  int32_t speed;
  NSString* details;
  LYSegment* segment;
  LYDirection direction;
}
- (BOOL) hasSegment;
- (BOOL) hasTimestamp;
- (BOOL) hasDirection;
- (BOOL) hasSpeed;
- (BOOL) hasDetails;
@property (readonly, retain) LYSegment* segment;
@property (readonly) int64_t timestamp;
@property (readonly) LYDirection direction;
@property (readonly) int32_t speed;
@property (readonly, retain) NSString* details;

+ (LYSegmentTraffic*) defaultInstance;
- (LYSegmentTraffic*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYSegmentTraffic_Builder*) builder;
+ (LYSegmentTraffic_Builder*) builder;
+ (LYSegmentTraffic_Builder*) builderWithPrototype:(LYSegmentTraffic*) prototype;

+ (LYSegmentTraffic*) parseFromData:(NSData*) data;
+ (LYSegmentTraffic*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYSegmentTraffic*) parseFromInputStream:(NSInputStream*) input;
+ (LYSegmentTraffic*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYSegmentTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYSegmentTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYSegmentTraffic_Builder : PBGeneratedMessage_Builder {
@private
  LYSegmentTraffic* result;
}

- (LYSegmentTraffic*) defaultInstance;

- (LYSegmentTraffic_Builder*) clear;
- (LYSegmentTraffic_Builder*) clone;

- (LYSegmentTraffic*) build;
- (LYSegmentTraffic*) buildPartial;

- (LYSegmentTraffic_Builder*) mergeFrom:(LYSegmentTraffic*) other;
- (LYSegmentTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYSegmentTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSegment;
- (LYSegment*) segment;
- (LYSegmentTraffic_Builder*) setSegment:(LYSegment*) value;
- (LYSegmentTraffic_Builder*) setSegmentBuilder:(LYSegment_Builder*) builderForValue;
- (LYSegmentTraffic_Builder*) mergeSegment:(LYSegment*) value;
- (LYSegmentTraffic_Builder*) clearSegment;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (LYSegmentTraffic_Builder*) setTimestamp:(int64_t) value;
- (LYSegmentTraffic_Builder*) clearTimestamp;

- (BOOL) hasDirection;
- (LYDirection) direction;
- (LYSegmentTraffic_Builder*) setDirection:(LYDirection) value;
- (LYSegmentTraffic_Builder*) clearDirection;

- (BOOL) hasSpeed;
- (int32_t) speed;
- (LYSegmentTraffic_Builder*) setSpeed:(int32_t) value;
- (LYSegmentTraffic_Builder*) clearSpeed;

- (BOOL) hasDetails;
- (NSString*) details;
- (LYSegmentTraffic_Builder*) setDetails:(NSString*) value;
- (LYSegmentTraffic_Builder*) clearDetails;
@end

@interface LYRoadTraffic : PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasRoad_:1;
  BOOL hasHref_:1;
  BOOL hasDesc_:1;
  int64_t timestamp;
  NSString* road;
  NSString* href;
  NSString* desc;
  NSMutableArray* mutableSegmentTrafficsList;
}
- (BOOL) hasRoad;
- (BOOL) hasTimestamp;
- (BOOL) hasHref;
- (BOOL) hasDesc;
@property (readonly, retain) NSString* road;
@property (readonly) int64_t timestamp;
@property (readonly, retain) NSString* href;
@property (readonly, retain) NSString* desc;
- (NSArray*) segmentTrafficsList;
- (LYSegmentTraffic*) segmentTrafficsAtIndex:(int32_t) index;

+ (LYRoadTraffic*) defaultInstance;
- (LYRoadTraffic*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYRoadTraffic_Builder*) builder;
+ (LYRoadTraffic_Builder*) builder;
+ (LYRoadTraffic_Builder*) builderWithPrototype:(LYRoadTraffic*) prototype;

+ (LYRoadTraffic*) parseFromData:(NSData*) data;
+ (LYRoadTraffic*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYRoadTraffic*) parseFromInputStream:(NSInputStream*) input;
+ (LYRoadTraffic*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYRoadTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYRoadTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYRoadTraffic_Builder : PBGeneratedMessage_Builder {
@private
  LYRoadTraffic* result;
}

- (LYRoadTraffic*) defaultInstance;

- (LYRoadTraffic_Builder*) clear;
- (LYRoadTraffic_Builder*) clone;

- (LYRoadTraffic*) build;
- (LYRoadTraffic*) buildPartial;

- (LYRoadTraffic_Builder*) mergeFrom:(LYRoadTraffic*) other;
- (LYRoadTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYRoadTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRoad;
- (NSString*) road;
- (LYRoadTraffic_Builder*) setRoad:(NSString*) value;
- (LYRoadTraffic_Builder*) clearRoad;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (LYRoadTraffic_Builder*) setTimestamp:(int64_t) value;
- (LYRoadTraffic_Builder*) clearTimestamp;

- (NSArray*) segmentTrafficsList;
- (LYSegmentTraffic*) segmentTrafficsAtIndex:(int32_t) index;
- (LYRoadTraffic_Builder*) replaceSegmentTrafficsAtIndex:(int32_t) index with:(LYSegmentTraffic*) value;
- (LYRoadTraffic_Builder*) addSegmentTraffics:(LYSegmentTraffic*) value;
- (LYRoadTraffic_Builder*) addAllSegmentTraffics:(NSArray*) values;
- (LYRoadTraffic_Builder*) clearSegmentTrafficsList;

- (BOOL) hasHref;
- (NSString*) href;
- (LYRoadTraffic_Builder*) setHref:(NSString*) value;
- (LYRoadTraffic_Builder*) clearHref;

- (BOOL) hasDesc;
- (NSString*) desc;
- (LYRoadTraffic_Builder*) setDesc:(NSString*) value;
- (LYRoadTraffic_Builder*) clearDesc;
@end

@interface LYCityTraffic : PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasCity_:1;
  int64_t timestamp;
  NSString* city;
  NSMutableArray* mutableRoadTrafficsList;
}
- (BOOL) hasCity;
- (BOOL) hasTimestamp;
@property (readonly, retain) NSString* city;
@property (readonly) int64_t timestamp;
- (NSArray*) roadTrafficsList;
- (LYRoadTraffic*) roadTrafficsAtIndex:(int32_t) index;

+ (LYCityTraffic*) defaultInstance;
- (LYCityTraffic*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYCityTraffic_Builder*) builder;
+ (LYCityTraffic_Builder*) builder;
+ (LYCityTraffic_Builder*) builderWithPrototype:(LYCityTraffic*) prototype;

+ (LYCityTraffic*) parseFromData:(NSData*) data;
+ (LYCityTraffic*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYCityTraffic*) parseFromInputStream:(NSInputStream*) input;
+ (LYCityTraffic*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYCityTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYCityTraffic*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYCityTraffic_Builder : PBGeneratedMessage_Builder {
@private
  LYCityTraffic* result;
}

- (LYCityTraffic*) defaultInstance;

- (LYCityTraffic_Builder*) clear;
- (LYCityTraffic_Builder*) clone;

- (LYCityTraffic*) build;
- (LYCityTraffic*) buildPartial;

- (LYCityTraffic_Builder*) mergeFrom:(LYCityTraffic*) other;
- (LYCityTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYCityTraffic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCity;
- (NSString*) city;
- (LYCityTraffic_Builder*) setCity:(NSString*) value;
- (LYCityTraffic_Builder*) clearCity;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (LYCityTraffic_Builder*) setTimestamp:(int64_t) value;
- (LYCityTraffic_Builder*) clearTimestamp;

- (NSArray*) roadTrafficsList;
- (LYRoadTraffic*) roadTrafficsAtIndex:(int32_t) index;
- (LYCityTraffic_Builder*) replaceRoadTrafficsAtIndex:(int32_t) index with:(LYRoadTraffic*) value;
- (LYCityTraffic_Builder*) addRoadTraffics:(LYRoadTraffic*) value;
- (LYCityTraffic_Builder*) addAllRoadTraffics:(NSArray*) values;
- (LYCityTraffic_Builder*) clearRoadTrafficsList;
@end

@interface LYCrontab : PBGeneratedMessage {
@private
  BOOL hasMinute_:1;
  BOOL hasHour_:1;
  BOOL hasDom_:1;
  BOOL hasMonth_:1;
  BOOL hasDow_:1;
  BOOL hasCronType_:1;
  int64_t minute;
  int64_t hour;
  int32_t dom;
  int32_t month;
  int32_t dow;
  LYCrontab_LYCronType cronType;
}
- (BOOL) hasCronType;
- (BOOL) hasMinute;
- (BOOL) hasHour;
- (BOOL) hasDom;
- (BOOL) hasMonth;
- (BOOL) hasDow;
@property (readonly) LYCrontab_LYCronType cronType;
@property (readonly) int64_t minute;
@property (readonly) int64_t hour;
@property (readonly) int32_t dom;
@property (readonly) int32_t month;
@property (readonly) int32_t dow;

+ (LYCrontab*) defaultInstance;
- (LYCrontab*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYCrontab_Builder*) builder;
+ (LYCrontab_Builder*) builder;
+ (LYCrontab_Builder*) builderWithPrototype:(LYCrontab*) prototype;

+ (LYCrontab*) parseFromData:(NSData*) data;
+ (LYCrontab*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYCrontab*) parseFromInputStream:(NSInputStream*) input;
+ (LYCrontab*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYCrontab*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYCrontab*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYCrontab_Builder : PBGeneratedMessage_Builder {
@private
  LYCrontab* result;
}

- (LYCrontab*) defaultInstance;

- (LYCrontab_Builder*) clear;
- (LYCrontab_Builder*) clone;

- (LYCrontab*) build;
- (LYCrontab*) buildPartial;

- (LYCrontab_Builder*) mergeFrom:(LYCrontab*) other;
- (LYCrontab_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYCrontab_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCronType;
- (LYCrontab_LYCronType) cronType;
- (LYCrontab_Builder*) setCronType:(LYCrontab_LYCronType) value;
- (LYCrontab_Builder*) clearCronType;

- (BOOL) hasMinute;
- (int64_t) minute;
- (LYCrontab_Builder*) setMinute:(int64_t) value;
- (LYCrontab_Builder*) clearMinute;

- (BOOL) hasHour;
- (int64_t) hour;
- (LYCrontab_Builder*) setHour:(int64_t) value;
- (LYCrontab_Builder*) clearHour;

- (BOOL) hasDom;
- (int32_t) dom;
- (LYCrontab_Builder*) setDom:(int32_t) value;
- (LYCrontab_Builder*) clearDom;

- (BOOL) hasMonth;
- (int32_t) month;
- (LYCrontab_Builder*) setMonth:(int32_t) value;
- (LYCrontab_Builder*) clearMonth;

- (BOOL) hasDow;
- (int32_t) dow;
- (LYCrontab_Builder*) setDow:(int32_t) value;
- (LYCrontab_Builder*) clearDow;
@end

@interface LYTrafficSub : PBGeneratedMessage {
@private
  BOOL hasExpires_:1;
  BOOL hasCity_:1;
  BOOL hasRoute_:1;
  BOOL hasCronTab_:1;
  BOOL hasOprType_:1;
  BOOL hasPubType_:1;
  int32_t expires;
  NSString* city;
  LYRoute* route;
  LYCrontab* cronTab;
  LYTrafficSub_LYOprType oprType;
  LYTrafficSub_LYPubType pubType;
}
- (BOOL) hasCity;
- (BOOL) hasRoute;
- (BOOL) hasOprType;
- (BOOL) hasPubType;
- (BOOL) hasExpires;
- (BOOL) hasCronTab;
@property (readonly, retain) NSString* city;
@property (readonly, retain) LYRoute* route;
@property (readonly) LYTrafficSub_LYOprType oprType;
@property (readonly) LYTrafficSub_LYPubType pubType;
@property (readonly) int32_t expires;
@property (readonly, retain) LYCrontab* cronTab;

+ (LYTrafficSub*) defaultInstance;
- (LYTrafficSub*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYTrafficSub_Builder*) builder;
+ (LYTrafficSub_Builder*) builder;
+ (LYTrafficSub_Builder*) builderWithPrototype:(LYTrafficSub*) prototype;

+ (LYTrafficSub*) parseFromData:(NSData*) data;
+ (LYTrafficSub*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYTrafficSub*) parseFromInputStream:(NSInputStream*) input;
+ (LYTrafficSub*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYTrafficSub*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYTrafficSub*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYTrafficSub_Builder : PBGeneratedMessage_Builder {
@private
  LYTrafficSub* result;
}

- (LYTrafficSub*) defaultInstance;

- (LYTrafficSub_Builder*) clear;
- (LYTrafficSub_Builder*) clone;

- (LYTrafficSub*) build;
- (LYTrafficSub*) buildPartial;

- (LYTrafficSub_Builder*) mergeFrom:(LYTrafficSub*) other;
- (LYTrafficSub_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYTrafficSub_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCity;
- (NSString*) city;
- (LYTrafficSub_Builder*) setCity:(NSString*) value;
- (LYTrafficSub_Builder*) clearCity;

- (BOOL) hasRoute;
- (LYRoute*) route;
- (LYTrafficSub_Builder*) setRoute:(LYRoute*) value;
- (LYTrafficSub_Builder*) setRouteBuilder:(LYRoute_Builder*) builderForValue;
- (LYTrafficSub_Builder*) mergeRoute:(LYRoute*) value;
- (LYTrafficSub_Builder*) clearRoute;

- (BOOL) hasOprType;
- (LYTrafficSub_LYOprType) oprType;
- (LYTrafficSub_Builder*) setOprType:(LYTrafficSub_LYOprType) value;
- (LYTrafficSub_Builder*) clearOprType;

- (BOOL) hasPubType;
- (LYTrafficSub_LYPubType) pubType;
- (LYTrafficSub_Builder*) setPubType:(LYTrafficSub_LYPubType) value;
- (LYTrafficSub_Builder*) clearPubType;

- (BOOL) hasExpires;
- (int32_t) expires;
- (LYTrafficSub_Builder*) setExpires:(int32_t) value;
- (LYTrafficSub_Builder*) clearExpires;

- (BOOL) hasCronTab;
- (LYCrontab*) cronTab;
- (LYTrafficSub_Builder*) setCronTab:(LYCrontab*) value;
- (LYTrafficSub_Builder*) setCronTabBuilder:(LYCrontab_Builder*) builderForValue;
- (LYTrafficSub_Builder*) mergeCronTab:(LYCrontab*) value;
- (LYTrafficSub_Builder*) clearCronTab;
@end

@interface LYTrafficPub : PBGeneratedMessage {
@private
  BOOL hasRouteId_:1;
  BOOL hasCityTraffic_:1;
  int32_t routeId;
  LYCityTraffic* cityTraffic;
}
- (BOOL) hasRouteId;
- (BOOL) hasCityTraffic;
@property (readonly) int32_t routeId;
@property (readonly, retain) LYCityTraffic* cityTraffic;

+ (LYTrafficPub*) defaultInstance;
- (LYTrafficPub*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYTrafficPub_Builder*) builder;
+ (LYTrafficPub_Builder*) builder;
+ (LYTrafficPub_Builder*) builderWithPrototype:(LYTrafficPub*) prototype;

+ (LYTrafficPub*) parseFromData:(NSData*) data;
+ (LYTrafficPub*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYTrafficPub*) parseFromInputStream:(NSInputStream*) input;
+ (LYTrafficPub*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYTrafficPub*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYTrafficPub*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYTrafficPub_Builder : PBGeneratedMessage_Builder {
@private
  LYTrafficPub* result;
}

- (LYTrafficPub*) defaultInstance;

- (LYTrafficPub_Builder*) clear;
- (LYTrafficPub_Builder*) clone;

- (LYTrafficPub*) build;
- (LYTrafficPub*) buildPartial;

- (LYTrafficPub_Builder*) mergeFrom:(LYTrafficPub*) other;
- (LYTrafficPub_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYTrafficPub_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRouteId;
- (int32_t) routeId;
- (LYTrafficPub_Builder*) setRouteId:(int32_t) value;
- (LYTrafficPub_Builder*) clearRouteId;

- (BOOL) hasCityTraffic;
- (LYCityTraffic*) cityTraffic;
- (LYTrafficPub_Builder*) setCityTraffic:(LYCityTraffic*) value;
- (LYTrafficPub_Builder*) setCityTrafficBuilder:(LYCityTraffic_Builder*) builderForValue;
- (LYTrafficPub_Builder*) mergeCityTraffic:(LYCityTraffic*) value;
- (LYTrafficPub_Builder*) clearCityTraffic;
@end

@interface LYDeviceReport : PBGeneratedMessage {
@private
  BOOL hasDeviceId_:1;
  BOOL hasDeviceName_:1;
  BOOL hasDeviceModel_:1;
  BOOL hasDeviceOsVersion_:1;
  BOOL hasDeviceToken_:1;
  NSString* deviceId;
  NSString* deviceName;
  NSString* deviceModel;
  NSString* deviceOsVersion;
  NSData* deviceToken;
}
- (BOOL) hasDeviceId;
- (BOOL) hasDeviceToken;
- (BOOL) hasDeviceName;
- (BOOL) hasDeviceModel;
- (BOOL) hasDeviceOsVersion;
@property (readonly, retain) NSString* deviceId;
@property (readonly, retain) NSData* deviceToken;
@property (readonly, retain) NSString* deviceName;
@property (readonly, retain) NSString* deviceModel;
@property (readonly, retain) NSString* deviceOsVersion;

+ (LYDeviceReport*) defaultInstance;
- (LYDeviceReport*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYDeviceReport_Builder*) builder;
+ (LYDeviceReport_Builder*) builder;
+ (LYDeviceReport_Builder*) builderWithPrototype:(LYDeviceReport*) prototype;

+ (LYDeviceReport*) parseFromData:(NSData*) data;
+ (LYDeviceReport*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYDeviceReport*) parseFromInputStream:(NSInputStream*) input;
+ (LYDeviceReport*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYDeviceReport*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYDeviceReport*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYDeviceReport_Builder : PBGeneratedMessage_Builder {
@private
  LYDeviceReport* result;
}

- (LYDeviceReport*) defaultInstance;

- (LYDeviceReport_Builder*) clear;
- (LYDeviceReport_Builder*) clone;

- (LYDeviceReport*) build;
- (LYDeviceReport*) buildPartial;

- (LYDeviceReport_Builder*) mergeFrom:(LYDeviceReport*) other;
- (LYDeviceReport_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYDeviceReport_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeviceId;
- (NSString*) deviceId;
- (LYDeviceReport_Builder*) setDeviceId:(NSString*) value;
- (LYDeviceReport_Builder*) clearDeviceId;

- (BOOL) hasDeviceToken;
- (NSData*) deviceToken;
- (LYDeviceReport_Builder*) setDeviceToken:(NSData*) value;
- (LYDeviceReport_Builder*) clearDeviceToken;

- (BOOL) hasDeviceName;
- (NSString*) deviceName;
- (LYDeviceReport_Builder*) setDeviceName:(NSString*) value;
- (LYDeviceReport_Builder*) clearDeviceName;

- (BOOL) hasDeviceModel;
- (NSString*) deviceModel;
- (LYDeviceReport_Builder*) setDeviceModel:(NSString*) value;
- (LYDeviceReport_Builder*) clearDeviceModel;

- (BOOL) hasDeviceOsVersion;
- (NSString*) deviceOsVersion;
- (LYDeviceReport_Builder*) setDeviceOsVersion:(NSString*) value;
- (LYDeviceReport_Builder*) clearDeviceOsVersion;
@end

@interface LYSamplePoint : PBGeneratedMessage {
@private
  BOOL hasAltitude_:1;
  BOOL hasTimestamp_:1;
  BOOL hasCourse_:1;
  BOOL hasSpCoordinate_:1;
  Float64 altitude;
  int64_t timestamp;
  int32_t course;
  LYCoordinate* spCoordinate;
}
- (BOOL) hasSpCoordinate;
- (BOOL) hasTimestamp;
- (BOOL) hasAltitude;
- (BOOL) hasCourse;
@property (readonly, retain) LYCoordinate* spCoordinate;
@property (readonly) int64_t timestamp;
@property (readonly) Float64 altitude;
@property (readonly) int32_t course;

+ (LYSamplePoint*) defaultInstance;
- (LYSamplePoint*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYSamplePoint_Builder*) builder;
+ (LYSamplePoint_Builder*) builder;
+ (LYSamplePoint_Builder*) builderWithPrototype:(LYSamplePoint*) prototype;

+ (LYSamplePoint*) parseFromData:(NSData*) data;
+ (LYSamplePoint*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYSamplePoint*) parseFromInputStream:(NSInputStream*) input;
+ (LYSamplePoint*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYSamplePoint*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYSamplePoint*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYSamplePoint_Builder : PBGeneratedMessage_Builder {
@private
  LYSamplePoint* result;
}

- (LYSamplePoint*) defaultInstance;

- (LYSamplePoint_Builder*) clear;
- (LYSamplePoint_Builder*) clone;

- (LYSamplePoint*) build;
- (LYSamplePoint*) buildPartial;

- (LYSamplePoint_Builder*) mergeFrom:(LYSamplePoint*) other;
- (LYSamplePoint_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYSamplePoint_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSpCoordinate;
- (LYCoordinate*) spCoordinate;
- (LYSamplePoint_Builder*) setSpCoordinate:(LYCoordinate*) value;
- (LYSamplePoint_Builder*) setSpCoordinateBuilder:(LYCoordinate_Builder*) builderForValue;
- (LYSamplePoint_Builder*) mergeSpCoordinate:(LYCoordinate*) value;
- (LYSamplePoint_Builder*) clearSpCoordinate;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (LYSamplePoint_Builder*) setTimestamp:(int64_t) value;
- (LYSamplePoint_Builder*) clearTimestamp;

- (BOOL) hasAltitude;
- (Float64) altitude;
- (LYSamplePoint_Builder*) setAltitude:(Float64) value;
- (LYSamplePoint_Builder*) clearAltitude;

- (BOOL) hasCourse;
- (int32_t) course;
- (LYSamplePoint_Builder*) setCourse:(int32_t) value;
- (LYSamplePoint_Builder*) clearCourse;
@end

@interface LYTrafficReport : PBGeneratedMessage {
@private
  NSMutableArray* mutablePointsList;
}
- (NSArray*) pointsList;
- (LYSamplePoint*) pointsAtIndex:(int32_t) index;

+ (LYTrafficReport*) defaultInstance;
- (LYTrafficReport*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYTrafficReport_Builder*) builder;
+ (LYTrafficReport_Builder*) builder;
+ (LYTrafficReport_Builder*) builderWithPrototype:(LYTrafficReport*) prototype;

+ (LYTrafficReport*) parseFromData:(NSData*) data;
+ (LYTrafficReport*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYTrafficReport*) parseFromInputStream:(NSInputStream*) input;
+ (LYTrafficReport*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYTrafficReport*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYTrafficReport*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYTrafficReport_Builder : PBGeneratedMessage_Builder {
@private
  LYTrafficReport* result;
}

- (LYTrafficReport*) defaultInstance;

- (LYTrafficReport_Builder*) clear;
- (LYTrafficReport_Builder*) clone;

- (LYTrafficReport*) build;
- (LYTrafficReport*) buildPartial;

- (LYTrafficReport_Builder*) mergeFrom:(LYTrafficReport*) other;
- (LYTrafficReport_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYTrafficReport_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) pointsList;
- (LYSamplePoint*) pointsAtIndex:(int32_t) index;
- (LYTrafficReport_Builder*) replacePointsAtIndex:(int32_t) index with:(LYSamplePoint*) value;
- (LYTrafficReport_Builder*) addPoints:(LYSamplePoint*) value;
- (LYTrafficReport_Builder*) addAllPoints:(NSArray*) values;
- (LYTrafficReport_Builder*) clearPointsList;
@end

@interface LYMsgOnAir : PBExtendableMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasVersion_:1;
  BOOL hasMsgId_:1;
  BOOL hasDeviceReport_:1;
  BOOL hasTrafficSub_:1;
  BOOL hasTrafficPub_:1;
  BOOL hasTrafficReport_:1;
  BOOL hasFromParty_:1;
  BOOL hasToParty_:1;
  BOOL hasMsgType_:1;
  BOOL hasRetCode_:1;
  int64_t timestamp;
  int32_t version;
  int32_t msgId;
  LYDeviceReport* deviceReport;
  LYTrafficSub* trafficSub;
  LYTrafficPub* trafficPub;
  LYTrafficReport* trafficReport;
  LYParty fromParty;
  LYParty toParty;
  LYMsgType msgType;
  LYRetCode retCode;
}
- (BOOL) hasVersion;
- (BOOL) hasMsgId;
- (BOOL) hasTimestamp;
- (BOOL) hasFromParty;
- (BOOL) hasToParty;
- (BOOL) hasMsgType;
- (BOOL) hasRetCode;
- (BOOL) hasDeviceReport;
- (BOOL) hasTrafficSub;
- (BOOL) hasTrafficPub;
- (BOOL) hasTrafficReport;
@property (readonly) int32_t version;
@property (readonly) int32_t msgId;
@property (readonly) int64_t timestamp;
@property (readonly) LYParty fromParty;
@property (readonly) LYParty toParty;
@property (readonly) LYMsgType msgType;
@property (readonly) LYRetCode retCode;
@property (readonly, retain) LYDeviceReport* deviceReport;
@property (readonly, retain) LYTrafficSub* trafficSub;
@property (readonly, retain) LYTrafficPub* trafficPub;
@property (readonly, retain) LYTrafficReport* trafficReport;

+ (LYMsgOnAir*) defaultInstance;
- (LYMsgOnAir*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LYMsgOnAir_Builder*) builder;
+ (LYMsgOnAir_Builder*) builder;
+ (LYMsgOnAir_Builder*) builderWithPrototype:(LYMsgOnAir*) prototype;

+ (LYMsgOnAir*) parseFromData:(NSData*) data;
+ (LYMsgOnAir*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYMsgOnAir*) parseFromInputStream:(NSInputStream*) input;
+ (LYMsgOnAir*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LYMsgOnAir*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LYMsgOnAir*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LYMsgOnAir_Builder : PBExtendableMessage_Builder {
@private
  LYMsgOnAir* result;
}

- (LYMsgOnAir*) defaultInstance;

- (LYMsgOnAir_Builder*) clear;
- (LYMsgOnAir_Builder*) clone;

- (LYMsgOnAir*) build;
- (LYMsgOnAir*) buildPartial;

- (LYMsgOnAir_Builder*) mergeFrom:(LYMsgOnAir*) other;
- (LYMsgOnAir_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LYMsgOnAir_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (int32_t) version;
- (LYMsgOnAir_Builder*) setVersion:(int32_t) value;
- (LYMsgOnAir_Builder*) clearVersion;

- (BOOL) hasMsgId;
- (int32_t) msgId;
- (LYMsgOnAir_Builder*) setMsgId:(int32_t) value;
- (LYMsgOnAir_Builder*) clearMsgId;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (LYMsgOnAir_Builder*) setTimestamp:(int64_t) value;
- (LYMsgOnAir_Builder*) clearTimestamp;

- (BOOL) hasFromParty;
- (LYParty) fromParty;
- (LYMsgOnAir_Builder*) setFromParty:(LYParty) value;
- (LYMsgOnAir_Builder*) clearFromParty;

- (BOOL) hasToParty;
- (LYParty) toParty;
- (LYMsgOnAir_Builder*) setToParty:(LYParty) value;
- (LYMsgOnAir_Builder*) clearToParty;

- (BOOL) hasMsgType;
- (LYMsgType) msgType;
- (LYMsgOnAir_Builder*) setMsgType:(LYMsgType) value;
- (LYMsgOnAir_Builder*) clearMsgType;

- (BOOL) hasRetCode;
- (LYRetCode) retCode;
- (LYMsgOnAir_Builder*) setRetCode:(LYRetCode) value;
- (LYMsgOnAir_Builder*) clearRetCode;

- (BOOL) hasDeviceReport;
- (LYDeviceReport*) deviceReport;
- (LYMsgOnAir_Builder*) setDeviceReport:(LYDeviceReport*) value;
- (LYMsgOnAir_Builder*) setDeviceReportBuilder:(LYDeviceReport_Builder*) builderForValue;
- (LYMsgOnAir_Builder*) mergeDeviceReport:(LYDeviceReport*) value;
- (LYMsgOnAir_Builder*) clearDeviceReport;

- (BOOL) hasTrafficSub;
- (LYTrafficSub*) trafficSub;
- (LYMsgOnAir_Builder*) setTrafficSub:(LYTrafficSub*) value;
- (LYMsgOnAir_Builder*) setTrafficSubBuilder:(LYTrafficSub_Builder*) builderForValue;
- (LYMsgOnAir_Builder*) mergeTrafficSub:(LYTrafficSub*) value;
- (LYMsgOnAir_Builder*) clearTrafficSub;

- (BOOL) hasTrafficPub;
- (LYTrafficPub*) trafficPub;
- (LYMsgOnAir_Builder*) setTrafficPub:(LYTrafficPub*) value;
- (LYMsgOnAir_Builder*) setTrafficPubBuilder:(LYTrafficPub_Builder*) builderForValue;
- (LYMsgOnAir_Builder*) mergeTrafficPub:(LYTrafficPub*) value;
- (LYMsgOnAir_Builder*) clearTrafficPub;

- (BOOL) hasTrafficReport;
- (LYTrafficReport*) trafficReport;
- (LYMsgOnAir_Builder*) setTrafficReport:(LYTrafficReport*) value;
- (LYMsgOnAir_Builder*) setTrafficReportBuilder:(LYTrafficReport_Builder*) builderForValue;
- (LYMsgOnAir_Builder*) mergeTrafficReport:(LYTrafficReport*) value;
- (LYMsgOnAir_Builder*) clearTrafficReport;
@end

